# Generated by Django 5.2.14 on 2026-06-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='decription',
            new_name='description',
        ),
    ]
